using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NEA.Classes
{
    enum TokenType
    {
        DECLARATION, ASSIGNMENT, REASSIGNMENT, ADDITION, TAKE, AWAY, MULTIPLICATION, DIVISION,
        GET, THE, REMAINDER, OF, MODULO, IF, ELSE, COUNT, WITH, FROM, BY, WHILE, LOOP, REPEAT, 
        FOR, EACH, IN, FUNCTION, SUBROUTINE_NAME, PROCEDURE, INPUTS, AS, VARIABLE, DATA_TYPE, TO, 
        STR_LITERAL, CHAR_LITERAL, INT_LITERAL, DEC_LITERAL, BOOL_LITERAL, LEFT_BRACKET, RIGHT_BRACKET,
        ADD, SUB, MUL, DIV, MOD, EXP, THEN, NEWLINE, TABSPACE, EQUAL, GREATER, LESS, GREATER_EQUAL, LESS_EQUAL,
        NOT_EQUAL, THAN, INPUT, PROMPT, PRINT, TIMES,
        AND, OR, NOT, BEGIN, END, RETURN, EON, EOF
    }
}
