using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NEA.Classes
{
    enum TokenType
    {
        DECLARATION, ASSIGNMENT, ADDITION, TAKE, AWAY, MULTIPLICATION, DIVISION,
        GET, THE, REMAINDER, OF, MODULO, IF, ELSE, COUNT, WITH, FROM, GOING, UP, DOWN, BY, WHILE, DO, REPEAT, 
        FOR, EACH, IN, FUNCTION, SUBROUTINE_NAME, PROCEDURE, INPUTS, AS, VARIABLE, DATA_TYPE, TO, 
        STR_LITERAL, CHAR_LITERAL, INT_LITERAL, DEC_LITERAL, BOOL_LITERAL, LEFT_BRACKET, RIGHT_BRACKET,
        ADD, SUB, MUL, DIV, MOD, EXP, THEN, NEWLINE, TABSPACE, EQUAL, GREATER, LESS, GREATER_EQUAL, LESS_EQUAL,
        NOT_EQUAL, THAN, INPUT, MESSAGE, PRINT, TIMES, DIVIDED, RAISE, POWER,
        AND, OR, NOT, END, RETURN, EON, EOF, COMMA, SQUARE_LEFT_BRACKET, SQUARE_RIGHT_BRACKET
    }
}
